### ISSUE TITLE
Question - without React

### ISSUE THREAD

**Issue by cancerberoSgx** [jfschwarz/substyle#34]
Forgive me for asking without even trying (yet) but I?m searching for something similar to this, but  library / DOM agnostic JSX based applications/document. 

Some crazy people like me is implementing JSX rendering in other mediums than the DOM, like string, json, Command line UI,  Pdf, PNG, etc. See [1]

In this context, I'm researching for libraries with similar APIs like yours (that's awesome) . In this case, I wonder:

 * could substyle run without react or similar library, just a JS application with UI rendered form JSX to JavaScript objects ? in particular, how much it depends on React.Component, state and lifecycle ?
 * is it dependent on HTML DOM or CSS standard properties ? In other words, can it render custom properties and work with other  JSX.IntrinsicElements than HTML's and other stylesheet properties than Standard CSS ?
 * (not so important) but, wandering how much depends on a dynamic medium. in other words, can I use it to generate a static HTML pages or PDFs ?

 I wonder if substyle is agnostic enough to take care of styles abstraction at the JSX code LEVEL and let the render implementation serialize the styles agnosticly enough so it can be impacted on different mediums like the CLI, DOM, static documents, etc (for example a CSS AST or classNames => CSSProperties map.

Thanks! will research, but I just wanted to ask your opinion about this first, Sorry for the noise, will close this in a couple of days. Keep it up!

[1]https://github.com/cancerberoSgx/typescript-ast-explorer/blob/72fc0bb6f305490a1b21fa64138f93acb8d6f41c/spec/blessed/gallery/CollapsibleDemo.tsx
https://cancerberosgx.github.io/jsx-explorer/
https://github.com/Yomguithereal/react-blessed, (this one depends on react - but as an example from other person)
 https://github.com/cancerberoSgx/jsx-alone

**Comment by jfschwarz** [comment]
Absolutely, the core of substyle, the [createSubstyle](https://github.com/jfschwarz/substyle/blob/master/packages/substyle/src/createSubstyle.js) function, does not depend on React at all. It implements the selection and merging of style definitions and offers dependency injection for mapping the resulting style definitions of each element to the final props object.

For supporting non-React use cases, it might make sense to extract that function into an own npm package without the React peer dependency. If you're really interested in that, I'll be happy to help. 🙌

**Comment by cancerberoSgx** [comment]
Nice ! thanks, will give a shot and try to separate it if I need you, will ask here if I have any trouble Keep it up!
