### ISSUE TITLE
Use of Symbol.iterator in library code is incomptible with IE11

### ISSUE THREAD

**Issue by cbergmiller** [jfschwarz/substyle#36]
The `omit` function in `src/utils.js` makes use of the `for...of` statement.

```javascript
export const omit = (obj, keys: string[]) => {
  const { ...other } = { ...obj }
  if (keys) {
    for (const key of keys) {
      delete other[key]
    }
  }
  return other
}
```

This gets compiled to the use of `Symbol.iterator` in the babel output.
I could not find a `Symbol` shim that worked in IE11 with your library. Or is there a way?
Would you be open to a more classic approach? For example:

```javascript
export const omit = (obj, keys: string[]) => {
    const other = Object.assign({}, obj);
    for (let i=0; i<keys.length;i++) {
        delete other[keys[i]]
    }
}
```
I assume `keys` will always be an array and the `for..of` iterator support is not needed?
I could create a pull request if you would be open for it.

**Comment by jfschwarz** [comment]
Absolutely. Anything that works and makes the library more easy to use. Thank you!
