### ISSUE TITLE
react and react-dom should be listed as peerDependencies, rather than dependencies

### ISSUE THREAD

**Issue by sjones6** [jfschwarz/substyle#79]
The package.json currently specifies `react` and `react-dom` as dependencies:

```
"dependencies": {
   ...
    "react": "^16.8.3",
    "react-dom": "^16.8.3"
}
```

In order to avoid ["Duplicate React"](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) errors when using hooks, the recommendation from the react team is to use `peerDependencies` to specify this:

> For example, maybe a library you’re using incorrectly specifies react as a dependency (rather than a peer dependency). Until that library is fixed, [Yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) is one possible workaround.

**Comment by jfschwarz** [comment]
I believe you're looking at the mono repo wrapper project's package.json. The [dependencies of the actual substyle package](https://github.com/jfschwarz/substyle/blob/master/packages/substyle/package.json) don't include React.

**Comment by sjones6** [comment]
Ah yep—my misunderstanding. Thanks for clarifying. Closing issue...
